"""Golden regression baseline for the prep-amortization work.

This freezes the current (pre-optimization) FrustraPy outputs so the prep
amortization (computing the per-structure data prep once and reusing it across a
saturation scan's N x 20 variants) can be proven to change no numbers. It loads
the committed fixtures under ``tests/data/prep_baseline/`` and asserts the current
code reproduces them. It must PASS now (proving the baseline is faithful) and stay
passing through the amortization work.

Panel: a single-chain structure (1crn) and a genuine multi-chain structure (1zni,
insulin, 4 chains with cross-chain contacts), all three modes, plus a small
saturation scan (single- and multi-chain). The stored tables are the ``lammps``
oracle; the native backend is checked against them.

The fixtures and this test are regenerated by
``tests/data/prep_baseline/generate_baseline.py``. See
``docs/PREP_AMORTIZATION_PLAN.md`` for the design.

NOTE on PATH: the engine spawns a bare ``python3`` subprocess, so run ``pytest``
from an activated venv (see conftest.py).
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import warnings

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
BASELINE = os.path.join(DATA, "prep_baseline")

with open(os.path.join(BASELINE, "manifest.json")) as _fh:
    MANIFEST = json.load(_fh)

SEQ_DIST = MANIFEST["seq_dist"]
STRUCT_PDB = {"1crn": os.path.join(DATA, "1crn.pdb"), "1zni": os.path.join(DATA, "1zni.pdb")}
MODES = ("configurational", "mutational", "singleresidue")

try:
    import frustrapy_native  # noqa: F401

    HAS_NATIVE = True
except ImportError:
    HAS_NATIVE = False

# Column layout (0-based) of the parsed FrustrationData tables.
#   contact (config/mut), 14 cols: Res1 Res2 ChainRes1 ChainRes2 DensityRes1
#     DensityRes2 AA1 AA2 NativeEnergy DecoyEnergy SDEnergy FrstIndex Welltype
#     FrstState
#   singleresidue, 8 cols: Res ChainRes DensityRes AA NativeEnergy DecoyEnergy
#     SDEnergy FrstIndex
_NUM_COLS = {
    "configurational": [4, 5, 8, 9, 10, 11],
    "mutational": [4, 5, 8, 9, 10, 11],
    "singleresidue": [2, 4, 5, 6, 7],
}
# Identity / class columns that must match exactly (residue, chain, amino acid,
# well type, and the frustration class) -- string equality, not numeric tolerance.
_ID_COLS = {
    "configurational": [0, 1, 2, 3, 6, 7, 12, 13],
    "mutational": [0, 1, 2, 3, 6, 7, 12, 13],
    "singleresidue": [0, 1, 3],
}
_FRST_COL = {"configurational": 11, "mutational": 11, "singleresidue": 7}

# CPU parity tolerance for the native backend vs the lammps oracle (the table
# prints to 3 decimals; allow a single last-digit rounding step).
_NATIVE_TOL = 1.5e-3


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def _rows(path):
    """Token-split data rows of a whitespace/tab-delimited table (skip header)."""
    with open(path) as fh:
        return [ln.split() for ln in fh.read().splitlines()[1:]]


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _spearman(a, b):
    def rank(xs):
        order = sorted(range(len(xs)), key=lambda i: xs[i])
        r = [0.0] * len(xs)
        for pos, i in enumerate(order):
            r[i] = float(pos)
        return r

    ra, rb = rank(a), rank(b)
    n = len(a)
    ma, mb = sum(ra) / n, sum(rb) / n
    cov = sum((ra[i] - ma) * (rb[i] - mb) for i in range(n))
    va = sum((x - ma) ** 2 for x in ra) ** 0.5
    vb = sum((x - mb) ** 2 for x in rb) ** 0.5
    return cov / (va * vb) if va and vb else 1.0


def _run(backend, mode, base, results_dir):
    """Run one calculate_frustration into a fresh scratch dir; return the table path."""
    import frustrapy

    src = STRUCT_PDB[base]
    if os.path.exists(results_dir):
        shutil.rmtree(results_dir)
    os.makedirs(results_dir)
    local = os.path.join(results_dir, os.path.basename(src))
    shutil.copy2(src, local)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        frustrapy.calculate_frustration(
            pdb_file=local, mode=mode, results_dir=results_dir, graphics=False,
            visualization=False, debug="ERROR", backend=backend, seq_dist=SEQ_DIST,
        )
    return os.path.join(results_dir, f"{base}.done", "FrustrationData", f"{base}.pdb_{mode}")


def _scan(base, targets, results_dir):
    """Run a saturation scan; return {(res, chain): token-rows of the variant table}."""
    import frustrapy
    from frustrapy.analysis.mutations import mutate_res_scan_parallel

    src = STRUCT_PDB[base]
    if os.path.exists(results_dir):
        shutil.rmtree(results_dir)
    os.makedirs(results_dir)
    local = os.path.join(results_dir, os.path.basename(src))
    shutil.copy2(src, local)
    residues = {}
    for res, chain in targets:
        residues.setdefault(chain, []).append(res)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        pdb, _, _, _ = frustrapy.calculate_frustration(
            pdb_file=local, mode="singleresidue", residues=residues,
            results_dir=results_dir, graphics=False, visualization=False,
            debug="ERROR", seq_dist=SEQ_DIST,
        )
        mutate_res_scan_parallel(
            pdb, targets=list(targets), split=True, method="threading", n_cpus=None
        )
    md = os.path.join(pdb.job_dir, "MutationsData")
    out = {}
    for res, chain in targets:
        f = os.path.join(md, f"singleresidue_Res{res}_threading_{chain}.txt")
        out[(res, chain)] = _rows(f)
    return out


def _scan_targets(base):
    """The (res_num, chain) targets stored in the manifest for a structure."""
    return [
        (info["res_num"], info["chain"])
        for info in MANIFEST["scans"].values()
        if info["structure"] == base
    ]


# --------------------------------------------------------------------------- #
# Fast: the committed fixtures are present and intact
# --------------------------------------------------------------------------- #
def test_baseline_fixtures_present_and_intact():
    """Every fixture named in the manifest exists with the recorded row count and
    sha256 (the baseline has not drifted or been partially committed)."""
    for name, info in {**MANIFEST["tables"], **MANIFEST["scans"]}.items():
        path = os.path.join(BASELINE, name)
        assert os.path.exists(path), f"missing baseline fixture: {name}"
        assert _sha256(path) == info["sha256"], f"baseline fixture changed: {name}"
        n = info.get("n_rows", info.get("n_variants"))
        with open(path) as fh:
            rows = sum(1 for _ in fh) - 1
        assert rows == n, f"{name}: {rows} rows, manifest says {n}"


def test_panel_covers_single_and_multi_chain():
    """The panel spans a single-chain and a genuine multi-chain structure, all
    three modes, and a multi-chain scan with a target in a non-default chain."""
    for base in ("1crn", "1zni"):
        for mode in MODES:
            assert f"{base}.pdb_{mode}" in MANIFEST["tables"]
    # 1zni configurational has cross-chain contacts (ChainRes1 != ChainRes2).
    rows = _rows(os.path.join(BASELINE, "1zni.pdb_configurational"))
    cross = sum(1 for r in rows if r[2] != r[3])
    assert cross > 0, "multi-chain fixture has no cross-chain contacts"
    # A scan target lives in chain B (not the first chain).
    assert any(c == "B" for _, c in _scan_targets("1zni"))


# --------------------------------------------------------------------------- #
# Slow: current code reproduces the baseline
# --------------------------------------------------------------------------- #
@pytest.mark.slow
@pytest.mark.parametrize("base", ["1crn", "1zni"])
@pytest.mark.parametrize("mode", list(MODES))
def test_lammps_reproduces_table(base, mode, tmp_path):
    """The default (lammps) backend reproduces the stored table token-for-token:
    same row count, same identity/class columns, zero numeric difference (the
    Linux binary is empirically deterministic)."""
    ref = _rows(os.path.join(BASELINE, f"{base}.pdb_{mode}"))
    got = _rows(_run("lammps", mode, base, str(tmp_path / f"l_{base}_{mode}")))
    assert len(got) == len(ref) > 0, f"row count {len(got)} vs {len(ref)}"
    for a, b in zip(ref, got):
        assert a == b, f"{base} {mode}: row differs\n  baseline {a}\n  current  {b}"

    # 5 Angstrom density table for the contact modes.
    if mode in ("configurational", "mutational"):
        adens_name = f"{base}.pdb_{mode}_5adens"
        adens_ref = os.path.join(BASELINE, adens_name)
        if os.path.exists(adens_ref):
            table = os.path.join(
                str(tmp_path / f"l_{base}_{mode}"), f"{base}.done",
                "FrustrationData", f"{base}.pdb_{mode}_5adens",
            )
            assert _rows(table) == _rows(adens_ref), f"{adens_name}: 5adens differs"


@pytest.mark.slow
@pytest.mark.skipif(not HAS_NATIVE, reason="native core not built (pip install ./native)")
@pytest.mark.parametrize("base", ["1crn", "1zni"])
@pytest.mark.parametrize("mode", list(MODES))
def test_native_reproduces_table(base, mode, tmp_path):
    """The native backend reproduces the stored lammps table: identical row count,
    identity, well type and class columns; numeric columns within the CPU parity
    tolerance; FrstIndex rank (Spearman) 1.0 and 100 percent sign agreement."""
    ref = _rows(os.path.join(BASELINE, f"{base}.pdb_{mode}"))
    got = _rows(_run("native", mode, base, str(tmp_path / f"n_{base}_{mode}")))
    assert len(got) == len(ref) > 0, f"row count {len(got)} vs {len(ref)}"

    max_d = 0.0
    for a, b in zip(ref, got):
        for c in _ID_COLS[mode]:
            assert a[c] == b[c], f"{base} {mode}: column {c} differs {a[c]} vs {b[c]}"
        for c in _NUM_COLS[mode]:
            max_d = max(max_d, abs(float(a[c]) - float(b[c])))
    assert max_d <= _NATIVE_TOL, f"{base} {mode}: max numeric diff {max_d}"

    fc = _FRST_COL[mode]
    ra = [float(r[fc]) for r in ref]
    rb = [float(r[fc]) for r in got]
    assert _spearman(ra, rb) >= 0.9999, f"{base} {mode}: FrstIndex Spearman low"
    for x, y in zip(ra, rb):
        if abs(x) > 1e-2 and abs(y) > 1e-2:
            assert (x > 0) == (y > 0), f"{base} {mode}: sign mismatch {x} vs {y}"


def _core_inputs(base, results_dir):
    """Materialize the native core inputs once: run a native calc to produce the
    coefficient/gamma files, then parse the structure and parameter tables into the
    kwargs ``frustrapy_native.compute_frustration`` consumes (minus mode/n_threads).
    Mirrors the prep boundary the amortized path reuses across variants."""
    from frustrapy.backends import native as nbk

    _run("native", "configurational", base, results_dir)
    job = os.path.join(results_dir, f"{base}.done")
    pdb_path = os.path.join(job, "FrustrationData", f"{base}.pdb")
    coord, res_type, chain_id, seqid, _chain_num, _letters = nbk._parse_structure(pdb_path)
    coeff = nbk._read_coeff(os.path.join(job, "fix_backbone_coeff.data"))
    gd, gw, gp, bg = nbk._read_gammas(job)
    return dict(
        coord=coord, res_type=res_type, chain_id=chain_id, res_seqid=seqid,
        gamma_direct=gd, gamma_water=gw, gamma_protein=gp, burial_gamma=bg,
        well_kappa=coeff["well_kappa"], kappa_sigma=coeff["kappa_sigma"],
        treshold=coeff["treshold"], well_r_min0=coeff["well_r_min0"],
        well_r_max0=coeff["well_r_max0"], well_r_min1=coeff["well_r_min1"],
        well_r_max1=coeff["well_r_max1"], burial_kappa=coeff["burial_kappa"],
        k_burial=coeff["k_burial"], contact_cutoff=coeff["contact_cutoff"],
        contact_min_sep=coeff["contact_min_sep"], seq_dist=SEQ_DIST,
        n_decoys=coeff["n_decoys"], seed=1,
    )


@pytest.mark.slow
@pytest.mark.skipif(not HAS_NATIVE, reason="native core not built (pip install ./native)")
@pytest.mark.parametrize("base", ["1crn", "1zni"])
@pytest.mark.parametrize("mode", list(MODES))
def test_native_geometry_reuse_bit_identical(base, mode, tmp_path):
    """The optional precomputed-geometry path (I2) is a numeric no-op: feeding the
    rho/contacts from ``prepare_geometry`` into ``compute_frustration`` reproduces the
    one-shot result bit-for-bit (max abs diff 0 on every column), single- and
    multi-chain, for all three modes. This is the no-regression proof that geometry
    reuse changes no numbers; the timing win is measured by the micro-benchmark."""
    import numpy as np
    import frustrapy_native as fn

    kw = _core_inputs(base, str(tmp_path / f"geo_{base}"))
    geo = fn.prepare_geometry(
        coord=kw["coord"], res_type=kw["res_type"], chain_id=kw["chain_id"],
        res_seqid=kw["res_seqid"], well_kappa=kw["well_kappa"],
        well_r_min0=kw["well_r_min0"], well_r_max0=kw["well_r_max0"],
        contact_cutoff=kw["contact_cutoff"], contact_min_sep=kw["contact_min_sep"],
        seq_dist=kw["seq_dist"],
    )
    one_shot = fn.compute_frustration(mode=mode, n_threads=1, **kw)
    reused = fn.compute_frustration(
        mode=mode, n_threads=1, rho=geo["rho"], contacts=geo["contacts"], **kw
    )
    keys = ["unit_i", "unit_j", "native_energy", "decoy_energy", "sd_energy",
            "frst_index", "rho"]
    for k in keys:
        assert np.array_equal(one_shot[k], reused[k]), (
            f"{base} {mode}: geometry reuse changed column {k}"
        )
    # rho-only reuse (singleresidue needs no contact list) is also a no-op.
    rho_only = fn.compute_frustration(mode=mode, n_threads=1, rho=geo["rho"], **kw)
    assert np.array_equal(one_shot["frst_index"], rho_only["frst_index"])


def _wt_job(base, mode, results_dir, chain=None):
    """Run a WT frustration calc (optionally restricted to one chain) and return
    ``(job_dir, pdb_base)``. The chain-restricted form mirrors the saturation scan,
    which computes each mutant over only the target residue's chain."""
    import frustrapy

    src = STRUCT_PDB[base]
    if os.path.exists(results_dir):
        shutil.rmtree(results_dir)
    os.makedirs(results_dir)
    local = os.path.join(results_dir, os.path.basename(src))
    shutil.copy2(src, local)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        pdb, _, _, _ = frustrapy.calculate_frustration(
            pdb_file=local, mode=mode, chain=chain, results_dir=results_dir,
            graphics=False, visualization=False, debug="ERROR", backend="native",
            seq_dist=SEQ_DIST,
        )
    return pdb.job_dir, pdb.pdb_base


@pytest.mark.slow
@pytest.mark.skipif(not HAS_NATIVE, reason="native core not built (pip install ./native)")
@pytest.mark.parametrize("base", ["1crn", "1zni"])
@pytest.mark.parametrize("mode", list(MODES))
def test_prepared_context_tables_match_baseline(base, mode, tmp_path):
    """The prepared-structure context (I1) reproduces the stored lammps tables for
    all three modes, single- and multi-chain: the per-residue density, contact list
    and FrstIndex computed once via prepare_structure and one compute_variant_frustration
    call match the golden baseline within the native CPU tolerance (Spearman 1.0,
    100 percent sign agreement), and equal the non-amortized native one-shot bit-for-bit."""
    import numpy as np
    from frustrapy.backends import native as nbk

    job, pbase = _wt_job(base, "configurational", str(tmp_path / f"prep_{base}"))
    prep = nbk.prepare_structure(job, pbase, SEQ_DIST)
    out = nbk.compute_variant_frustration(prep, mode, res_type=prep.res_type, n_threads=1)

    ref = _rows(os.path.join(BASELINE, f"{base}.pdb_{mode}"))
    fc = _FRST_COL[mode]
    got = list(out["frst_index"])
    assert len(got) == len(ref) > 0, f"{base} {mode}: row count {len(got)} vs {len(ref)}"
    ref_frst = [float(r[fc]) for r in ref]
    max_d = max(abs(a - b) for a, b in zip(ref_frst, got))
    assert max_d <= _NATIVE_TOL, f"{base} {mode}: prepared FrstIndex max diff {max_d}"
    assert _spearman(ref_frst, got) >= 0.9999, f"{base} {mode}: prepared Spearman low"
    for x, y in zip(ref_frst, got):
        if abs(x) > 1e-2 and abs(y) > 1e-2:
            assert (x > 0) == (y > 0), f"{base} {mode}: sign mismatch {x} vs {y}"

    # The geometry-reused (prepared) result equals the non-amortized native one-shot
    # bit-for-bit -- prep amortization changes no numbers (CPU max|dFrstIndex| = 0).
    import frustrapy_native as fn
    kw = _core_inputs(base, str(tmp_path / f"oneshot_{base}"))
    one = fn.compute_frustration(mode=mode, n_threads=1, **kw)
    assert np.array_equal(np.asarray(got), one["frst_index"]), (
        f"{base} {mode}: prepared != native one-shot"
    )


@pytest.mark.slow
@pytest.mark.skipif(not HAS_NATIVE, reason="native core not built (pip install ./native)")
@pytest.mark.parametrize("base", ["1crn", "1zni"])
def test_prepared_context_scan_matches_baseline(base, tmp_path):
    """The amortized saturation scan (prep once per chain, then a res_type swap per
    variant reusing the cached geometry) reproduces the golden per-variant FrstIndex
    within the native CPU tolerance with full sign agreement, selects the correct
    (res_num, chain) per target (multi-chain), and -- for the non-glycine variants
    that are a pure identity swap -- equals a fresh native compute bit-for-bit
    (CPU max|dFrstIndex| = 0), proving geometry reuse changes no numbers."""
    import numpy as np
    from frustrapy.analysis.mutations import AMINO_ACIDS
    from frustrapy.backends import native as nbk

    for (res, chain) in _scan_targets(base):
        job, pbase = _wt_job(
            base, "singleresidue", str(tmp_path / f"scan_{base}_{res}_{chain}"), chain=chain
        )
        prep = nbk.prepare_structure(job, pbase, SEQ_DIST)
        idx = prep.site_index(res, chain)
        ref = _rows(os.path.join(BASELINE, f"scan_{base}_Res{res}_{chain}.txt"))
        assert len(ref) == len(AMINO_ACIDS) == 20

        for k, aa in enumerate(AMINO_ACIDS):
            out = nbk.compute_variant_frustration(
                prep, "singleresidue", site=(res, chain), new_aa=aa, n_threads=1
            )
            fi = float(out["frst_index"][idx])
            ref_aa, ref_fi = ref[k][2], float(ref[k][3])
            assert nbk._THREE_TO_ONE[aa] == ref_aa, (
                f"{base} Res{res}/{chain}: AA order {aa} vs {ref_aa}"
            )
            assert abs(fi - ref_fi) <= _NATIVE_TOL, (
                f"{base} Res{res}/{chain} {aa}: FrstIndex {fi} vs baseline {ref_fi}"
            )
            if abs(fi) > 1e-2 and abs(ref_fi) > 1e-2:
                assert (fi > 0) == (ref_fi > 0), (
                    f"{base} Res{res}/{chain} {aa}: sign mismatch {fi} vs {ref_fi}"
                )
            # Non-glycine variant: the reused-geometry result is bit-for-bit a fresh
            # native recompute on the same coords (no precomputed geometry passed).
            if prep.resnames[idx] != "GLY" and aa != "GLY":
                rt = np.array(prep.res_type, dtype=np.int32)
                rt[idx] = nbk._aa_to_res_type(aa)
                fresh = nbk.compute_variant_frustration(
                    prep, "singleresidue", res_type=rt, n_threads=1
                )
                # Drop the cached geometry to force a recompute, then compare.
                import frustrapy_native as fn
                gd, gw, gp, bg = prep.gammas
                recompute = fn.compute_frustration(
                    coord=prep.coord, res_type=rt, chain_id=prep.chain_id,
                    res_seqid=prep.seqid, gamma_direct=gd, gamma_water=gw,
                    gamma_protein=gp, burial_gamma=bg, mode="singleresidue",
                    well_kappa=prep.coeff["well_kappa"], kappa_sigma=prep.coeff["kappa_sigma"],
                    treshold=prep.coeff["treshold"], well_r_min0=prep.coeff["well_r_min0"],
                    well_r_max0=prep.coeff["well_r_max0"], well_r_min1=prep.coeff["well_r_min1"],
                    well_r_max1=prep.coeff["well_r_max1"], burial_kappa=prep.coeff["burial_kappa"],
                    k_burial=prep.coeff["k_burial"], contact_cutoff=prep.coeff["contact_cutoff"],
                    contact_min_sep=prep.coeff["contact_min_sep"], seq_dist=SEQ_DIST,
                    n_decoys=prep.coeff["n_decoys"], seed=1, n_threads=1,
                )
                assert np.array_equal(fresh["frst_index"], recompute["frst_index"]), (
                    f"{base} Res{res}/{chain} {aa}: amortized != fresh recompute"
                )


@pytest.mark.slow
@pytest.mark.parametrize("base", ["1crn", "1zni"])
def test_saturation_scan_reproduces(base, tmp_path):
    """A saturation scan reproduces the per-variant FrstIndex token-for-token, and
    selects the correct (res_num, chain) per target (multi-chain site selection)."""
    targets = _scan_targets(base)
    got = _scan(base, targets, str(tmp_path / f"scan_{base}"))
    for (res, chain) in targets:
        ref = _rows(os.path.join(BASELINE, f"scan_{base}_Res{res}_{chain}.txt"))
        cur = got[(res, chain)]
        assert len(cur) == len(ref) == 20, f"{base} Res{res}/{chain}: variant count"
        for a, b in zip(ref, cur):
            assert a == b, f"{base} Res{res}/{chain}: row differs {a} vs {b}"
        # Chain-correct site selection: every variant row is the target site.
        for r in cur:
            assert int(r[0]) == res and r[1] == chain, (
                f"{base} Res{res}/{chain}: wrong site in row {r}"
            )
