"""ChimeraX command-script (``.cxc``) generator.

Produces the same frustration visualization as the PyMOL ``.pml`` generator
(``pymol_script.py``) for all three modes, so a user sees the same contacts and
the same class colors in ChimeraX as in PyMOL / the Plotly plots.

Configurational / mutational: the red/green contacts are written as a ChimeraX
pseudobond file (``.pb``) between the two CA atoms, colored by frustration class
(highly = red, minimally = green). The companion ``.cxc`` opens the structure,
shows it as a cartoon, and opens the ``.pb``.

Single-residue: each residue's cartoon is colored by its single-residue class
(red / gray / green at the -1 / 0.58 cutoffs), emitted as ``color`` commands.

ChimeraX rendering is a maintainer step (no headless ChimeraX in CI); the
generated commands/selections/colors are asserted programmatically -- the
per-class contact/residue counts match the parsed table and the PyMOL script.
"""

import os
from collections import OrderedDict
from typing import List, Optional

from .frustration_data import (
    ContactLink,
    ResidueColor,
    contact_links_from_df,
    read_table,
    residue_colors_from_df,
)

# class -> ChimeraX color name.
_CXC_CLASS_COLOR = {"highly": "red", "minimally": "green", "neutral": "gray"}

# pseudobond radius (matches the 0.05-ish thin links in the PyMOL view, scaled
# up so ChimeraX renders them visibly between CA atoms).
_PB_RADIUS = 0.2


def _atom_spec(chain: str, res: str) -> str:
    """ChimeraX atom spec for a residue's CA atom, e.g. ``/A:41@CA``."""
    return f"/{chain}:{res}@CA"


def generate_pb(links: List[ContactLink]) -> str:
    """Build a ChimeraX pseudobond (``.pb``) file from contact links.

    One pseudobond per red/green contact between the two CA atoms, in table
    order, colored by frustration class.
    """
    parts = [
        "; ChimeraX pseudobond file generated by FrustraPy\n",
        "; halfbond = false\n",
        f"; radius = {_PB_RADIUS}\n",
        "; dashes = 0\n",
    ]
    for link in links:
        parts.append(
            f"{_atom_spec(link.chain1, link.res1)} "
            f"{_atom_spec(link.chain2, link.res2)} {link.color}\n"
        )
    return "".join(parts)


def generate_contact_cxc(pdb_base: str, pb_filename: str) -> str:
    """Build the ``.cxc`` that opens the structure and the pseudobond file."""
    return (
        f"open {pdb_base}.pdb\n"
        "hide atoms\n"
        "show cartoon\n"
        "color light gray\n"
        f"open {pb_filename}\n"
    )


def generate_singleresidue_cxc(residues: List[ResidueColor], pdb_base: str) -> str:
    """Build a per-residue-coloring ``.cxc`` for single-residue mode.

    Residues are grouped by (chain, class) into one ``color`` command each, so
    the script stays compact and the per-class residue counts are recoverable.
    """
    # group residues by (chain, color) preserving first-seen order
    groups: "OrderedDict[tuple, List[str]]" = OrderedDict()
    for res in residues:
        col = _CXC_CLASS_COLOR[res.state]
        groups.setdefault((res.chain, col), []).append(res.res)

    parts = [
        f"open {pdb_base}.pdb\n",
        "hide atoms\n",
        "show cartoon\n",
        "color light gray\n",
    ]
    for (chain, col), reslist in groups.items():
        spec = f"/{chain}:" + ",".join(reslist)
        parts.append(f"color {spec} {col}\n")
    return "".join(parts)


def write_cxc(
    table_path: str,
    out_cxc_path: str,
    pdb_base: str,
    mode: str,
) -> List[str]:
    """Generate a ``.cxc`` (and ``.pb`` for contacts) from a parsed table.

    Returns the list of paths written.
    """
    df = read_table(table_path)
    out_dir = os.path.dirname(os.path.abspath(out_cxc_path))
    os.makedirs(out_dir, exist_ok=True)
    written = []

    if mode == "singleresidue":
        content = generate_singleresidue_cxc(residue_colors_from_df(df), pdb_base)
        with open(out_cxc_path, "w") as fh:
            fh.write(content)
        written.append(out_cxc_path)
    else:
        links = contact_links_from_df(df)
        pb_path = os.path.splitext(out_cxc_path)[0] + ".pb"
        with open(pb_path, "w") as fh:
            fh.write(generate_pb(links))
        written.append(pb_path)
        with open(out_cxc_path, "w") as fh:
            fh.write(generate_contact_cxc(pdb_base, os.path.basename(pb_path)))
        written.append(out_cxc_path)

    return written
